const colors = {
  light: {
    text: "#1A0533",
    tint: "#7C3AED",
    background: "#F5F3FF",
    foreground: "#1A0533",
    card: "#FFFFFF",
    cardForeground: "#1A0533",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#EDE9FE",
    secondaryForeground: "#5B21B6",
    muted: "#F3F0FF",
    mutedForeground: "#6B7280",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#DDD6FE",
    input: "#EDE9FE",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    info: "#8B5CF6",
    infoForeground: "#FFFFFF",
    gradientStart: "#2D1B69",
    gradientEnd: "#7C3AED",
  },
  dark: {
    text: "#F5F3FF",
    tint: "#A78BFA",
    background: "#0D0720",
    foreground: "#F5F3FF",
    card: "#160D30",
    cardForeground: "#F5F3FF",
    primary: "#8B5CF6",
    primaryForeground: "#FFFFFF",
    secondary: "#2D1B69",
    secondaryForeground: "#C4B5FD",
    muted: "#1E1040",
    mutedForeground: "#9CA3AF",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2D1B69",
    input: "#2D1B69",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    info: "#8B5CF6",
    infoForeground: "#FFFFFF",
    gradientStart: "#0D0720",
    gradientEnd: "#2D1B69",
  },
  radius: 14,
};

export default colors;
