const colors = {
  light: {
    text: "#0F172A",
    tint: "#1B4FD8",
    background: "#F0F4FF",
    foreground: "#0F172A",
    card: "#FFFFFF",
    cardForeground: "#0F172A",
    primary: "#1B4FD8",
    primaryForeground: "#FFFFFF",
    secondary: "#EEF2FF",
    secondaryForeground: "#1B4FD8",
    muted: "#F1F5F9",
    mutedForeground: "#64748B",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#CBD5E1",
    input: "#E2E8F0",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
    gradientStart: "#0D2B7E",
    gradientEnd: "#1B4FD8",
  },
  dark: {
    text: "#F0F4FF",
    tint: "#60A5FA",
    background: "#070D1F",
    foreground: "#F0F4FF",
    card: "#111829",
    cardForeground: "#F0F4FF",
    primary: "#3B82F6",
    primaryForeground: "#FFFFFF",
    secondary: "#1E2D50",
    secondaryForeground: "#93C5FD",
    muted: "#1A2440",
    mutedForeground: "#94A3B8",
    accent: "#F59E0B",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#1E3057",
    input: "#1E3057",
    success: "#10B981",
    successForeground: "#FFFFFF",
    warning: "#F59E0B",
    warningForeground: "#FFFFFF",
    info: "#3B82F6",
    infoForeground: "#FFFFFF",
    gradientStart: "#070D1F",
    gradientEnd: "#0D2B7E",
  },
  radius: 14,
};

export default colors;
